name: Setup Node.js and install dependencies
description: 'Setup Node.js and install dependencies using pnpm'

inputs:
  dir:
    description: 'Directory to run the install command in'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: cd ${{ inputs.dir }} && corepack enable pnpm && pnpm install --frozen-lockfile
      shell: bash
