name: Playwright Tests
on:
  push:
    branches: [ main ]
    paths:
      - remix-kysely-d1/**
      - .github/**
  pull_request:
    branches: [ main ]
    paths:
      - remix-kysely-d1/**
      - .github/**

jobs:
  test:
    defaults:
      run:
        working-directory: remix-kysely-d1
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./actions/setup
      with:
        dir: remix-kysely-d1
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm task test:e2e
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
