name: Playwright Tests
on:
  push:
    branches: [ main, master ]
    paths:
      - remix-kysely-d1/**
      - .github/**
  pull_request:
    branches: [ main, master ]
    paths:
      - remix-kysely-d1/**
      - .github/**

jobs:
  test:
    defaults:
      run:
        working-directory: remix-kysely-d1
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: corepack enable pnpm && pnpm install --frozen-lockfile
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm task test:e2e
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
